apiVersion: batch/v1
kind: CronJob
metadata:
  name: record-bfm
  labels:
    app: record-bfm
spec:
  timeZone: "Europe/Berlin"
  schedule: "59 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: record-bfm
        spec:
          containers:
            - image: eu-frankfurt-1.ocir.io/frs4lzee0jfi/record-bfm:latest
              name: record-bfm
              securityContext:
                privileged: true
              env:
                - name: RCLONE_ONEDRIVE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: record-bfm
                      key: RCLONE_ONEDRIVE_TOKEN
                - name: RCLONE_ONEDRIVE_DRIVEID
                  valueFrom:
                    secretKeyRef:
                      name: record-bfm
                      key: RCLONE_ONEDRIVE_DRIVEID

          imagePullSecrets:
            - name: registry-secret
          restartPolicy: OnFailure
